### ISSUE TITLE
Dynatrace nginx agent hanging nginx for some routes on restart

### ISSUE THREAD

**Issue by tinygrasshopper** [dynatrace-innovationlab/bosh-oneagent-release#1]
We are facing a situation in which the nginx stops responding to routes specified by https://github.com/cloudfoundry/cloud_controller_ng/blob/e7e6ed316a89bb578ecec0aedc88fb61b8fe362c/bosh/jobs/cloud_controller_ng/templates/nginx.conf.erb#L191, when restarted. This behavior is not seen if the addon is not installed.  The requests we notice fail need to have a 
multipart/form-data header

This are not responded to by nginx:
```
$ curl -H"Content-Type: multipart/form-data; boundary=o" -XPUT -d "foo" https://URL/v2/apps/70964c35-045e-4b0e-bed9-c1794ebbff1/bits?async=true
```

But this one is:
```
$ curl -H"Content-Type: multipart/form-data; boundary=o" -XPUT -d "foo" https://URL/v2/apps/70964c35-045e-4b0e-bed9-c1794ebbff1/something_else?async=true
```

And this one is:
```
$ curl  -XPUT -d "foo" https://URL/v2/apps/70964c35-045e-4b0e-bed9-c1794ebbff1/bits?async=true
```

**Comment by aloismayr** [comment]
Thanks @tinygrasshopper 

We are tracking an internal ticket on this issue. I'll let you know about updates on this item.

**Comment by aloismayr** [comment]
We found this issue occurs if an outdated http-upload-module for nginx was used. The module with the latest patch in the 2.2 branch fixes the issue. Please review this issue of the http-upload-module project. https://github.com/cloudfoundry/capi-release/issues/61 

As soon as the cloud_controller ships the patched module it should work.
